sonar.projectKey=bidmart-listing-query-service
sonar.projectName=BidMart Listing Query Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=build/classes/java/main
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
sonar.sourceEncoding=UTF-8
