server.port=${PORT:8082}
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${LISTING_QUERY_DB_URL:${SPRING_DATASOURCE_URL}}
spring.datasource.username=${LISTING_QUERY_DB_USERNAME:${SPRING_DATASOURCE_USERNAME}}
spring.datasource.password=${LISTING_QUERY_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
